### ISSUE TITLE
usage of add_subdirectory prevents library from being consumed by FetchContent

### ISSUE THREAD

**Issue by QuantumFelidae** [stdgraph/graph-v2#111]
Thanks for this work!

When attempting to consume this library through FetchContent as such:
```
FetchContent_Declare(
	stdgraph
	GIT_REPOSITORY https://github.com/stdgraph/graph-v2.git
	GIT_TAG master

)

FetchContent_MakeAvailable(stdgraph)
```

One will experience errors such as:
```
Make Error at out/build/x64-debug/_deps/stdgraph-src/cmake/FetchFMT.cmake:23 (add_subdirectory):
1> [CMake]   add_subdirectory not given a binary directory but the given source
1> [CMake]   directory "C:/dev/qmatpp/out/build/x64-debug/_deps/fmt-src" is not a
1> [CMake]   subdirectory of "C:/dev/qmatpp/out/build/x64-debug/_deps/stdgraph-src".
1> [CMake]   When specifying an out-of-tree source a binary directory must be explicitly
1> [CMake]   specified.
```
When a library already being consumed through FetchContent introduces further dependencies through FetchContent, those dependencies are placed adjacent to the consuming library in the same `_deps` folder. As such, the use of `add_subdirectory` will result in the above error.

Considering `graph-v2/cmake/FetchCatch.cmake`:

```
message(STATUS "Cloning External Project: catch2")

FetchContent_Declare(
    catch2
    GIT_REPOSITORY https://github.com/catchorg/Catch2.git
    GIT_TAG        v3.5.2
)

FetchContent_GetProperties(catch2)
if(NOT catch2_POPULATED)
  FetchContent_Populate(
    catch2
  )
endif()

set(CATCH2_SOURCE_DIR "${catch2_SOURCE_DIR}")
set(CATCH2_INCLUDE_DIR "${catch2_INCLUDE_DIR}")

FetchContent_MakeAvailable(catch2)
add_subdirectory(${catch2_SOURCE_DIR})
```

From the CMake documentation, I believe that the populated check is not required when using `MakeAvailable`:

> If the dependency has already been populated earlier in this run, set the <lowercaseName>_POPULATED, <lowercaseName>_SOURCE_DIR and <lowercaseName>_BINARY_DIR variables in the same way as a call to [FetchContent_GetProperties()](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_getproperties), then skip the remaining steps below and move on to the next dependency in the list. [src](https://cmake.org/cmake/help/latest/module/FetchContent.html)

Second, I believe that the `add_subdirectory` call that is introducing the issue at hand is not needed, as `MakeAvailable` should automatically call `add_subdirectory`:

> If the dependency was not satisfied by a provider or a [find_package()](https://cmake.org/cmake/help/latest/command/find_package.html#command:find_package) call, FetchContent_MakeAvailable() then uses the following logic to make the dependency available:
> * .... (Other steps) ...
> * If the top directory of the populated content contains a CMakeLists.txt file, call [add_subdirectory()](https://cmake.org/cmake/help/latest/command/add_subdirectory.html#command:add_subdirectory) to add it to the main build. It is not an error for there to be no CMakeLists.txt file, which allows the command to be used for dependencies that make downloaded content available at a known location, but which do not need or support being added directly to the build. [src](https://cmake.org/cmake/help/latest/module/FetchContent.html)

In my experience, the automatic `add_subdirectory` does not introduce the above error.

I am happy to open a PR to introduce these changes, but I wanted to confirm that my interpretation of the build setup was correct first. Thanks.

**Comment by neoblizz** [comment]
Thanks for this, this is very timely.

**Comment by QuantumFelidae** [comment]
Thanks!
