### ISSUE TITLE
Change /// style Doxygen comments to our standard style

### ISSUE THREAD

**Issue by pratzl** [stdgraph/graph-v2#58]
2 styles of Doxygen comments exist in our code and we should change it to be consistent. We've selected the /** ... */ style so all lines that start wtih /// need to be changed.

**Comment by pratzl** [comment]
It's marked as Done.
Is there a difference between "Done" and "Closed"?


Sent from Outlook<http://aka.ms/weboutlook>

**Comment by neoblizz** [comment]
Closing the issue means it is not active and will automatically move it to the "done" in the project board.
